### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by 0x6d617474** [magmaticlabs/obsidian#1]
The following are features that will eventually make their way into the project: 

*Basic Structure*
 - [x] Creation of organizations to handle multi-tenancy
 - [x] Creation of multiple repositories per organization to organize packages
 - [x] Creation of packages to hold source information and metadata
 - [x] Creation of builds to process source code into a distributable archive
 - [x] Manual processing of builds via commands

*Users and Authentication*
 - [x] Basic username/password authentication
 - [x] Cookie-based authentication for short-term access
 - [x] Token-based authentication for long-term access
 - [ ] Optional integration with Active Directory
 - [ ] Further authentication integration options

*Build Quality-Of-Life Features*  
 - [x] Job queue to process jobs as soon as possible
 - [x] Access to build logs via API
 - [x] Pruning of archive files via `.pkgmanifest` file
 - [x] Customizing build chain via Makefiles
 - [ ]  Webhook endpoint for responsive creation of builds
 - [ ] Latest-tag builds
 - [ ] Scheduled builds (weekly/nightly)
 - [ ] Slack notifications

*Misc*
 - [ ] Parsing of readme.txt to send in manifest
 - [ ] Telemetry from plugin for active installation information
 - [ ] Tracking number of downloads
 - [ ] Adding icon/banner/screenshots to packages

*Advanced Features*
 - [ ] Limiting access via access codes
 - [ ] Limiting access via licenses
